import {randomUUID} from 'node:crypto';
import {validate,hash,same,fail} from './contracts.js';
// The gateway never owns this dispatcher. Only explicit formal submissions do.
export class PeerFormalActions{
 constructor({peer,dispatcher,query=null,isEnabled=()=>true}){if(!peer||!dispatcher||query!==null&&typeof query!=='function')throw Error('Explicit peer/domain ports required');Object.assign(this,{peer,dispatcher,query,isEnabled});}
 async allowed(actor,record){const cap=this.dispatcher.capabilities.get(record.capability);if(!cap||cap.implementation.kind!=='function'||typeof cap.revalidate!=='function'||typeof cap.verify!=='function'||await cap.authorize(actor,record.input)!==true)throw fail('PEER_FORMAL_DENIED','Current formal capability access unavailable',403);return cap;}
 async read(tx,actor,id){const r=await tx.get('formal',id),c=await this.peer.channel(tx,actor,r.channelId);if(!same(await this.peer.who(actor),r.actor))throw fail('PEER_FORMAL_DENIED','Formal receipt belongs to another principal',403);await this.peer.permit(actor,'formal.read',{channel:c,record:r});return r;}
 async view(actor,r){const cap=await this.allowed(actor,r);let result=null;if(r.state==='confirmed')result=await cap.revalidate(r.input,r.result,{actor,callId:r.effectKey});return {id:r.id,state:r.state==='admitted'?'unknown':r.state,effectKey:r.effectKey,capability:r.capability,messageIds:r.messageIds,result};}
 async run(actor,operation,input){if(!['formal.submit','formal.result','formal.lookup','formal.reconcile'].includes(operation))throw fail('PEER_OPERATION','Unknown formal operation');const p=this.peer,i=validate(operation,input);
  if(operation==='formal.lookup'){const r=await p.store.transaction(async tx=>{const c=await p.channel(tx,actor,i.channelId),key=hash([c.id,await p.who(actor),i.requestKey]),ref=await tx.get('formal-key',key,false);return ref?this.read(tx,actor,ref.id):null;});return r?{status:'recorded',receipt:await this.view(actor,r)}:{status:'unknown'};}
  if(operation==='formal.result'){const r=await p.store.transaction(tx=>this.read(tx,actor,i.id));return this.view(actor,r);}
  if(operation==='formal.reconcile'){const r=await p.store.transaction(tx=>this.read(tx,actor,i.id));if(r.state==='confirmed')return this.view(actor,r);if(!this.query)throw fail('PEER_QUERY_UNAVAILABLE','Original domain effect query required',409);const cap=await this.allowed(actor,r);const result=await this.query({actor,capability:r.capability,input:r.input,effectKey:r.effectKey});if(result?.status!=='confirmed')return this.view(actor,r);if(!cap.validateOutput(result.result)||cap.verify&&await cap.verify(r.input,result.result,{actor,callId:r.effectKey})!==true)throw fail('PEER_OUTCOME','Queried domain outcome not verified',422);await this.finish(r,'confirmed',result.result);return this.view(actor,{...r,state:'confirmed',result:result.result});}
  if(await this.isEnabled()!==true)throw fail('PEER_DISABLED','Formal promotion disabled',503);
  let fresh=false;const r=await p.store.transaction(async tx=>{const c=await p.channel(tx,actor,i.channelId,{write:true});await p.grant(tx,c,i.grantId,{actor,type:'formal.submit'});await p.permit(actor,operation,{channel:c,input:i});if(i.subjectVersion!==c.subjectVersion||!c.allowedCapabilities.includes(i.capability))throw fail('PEER_SCOPE','Formal action outside current subject or capability scope',403);for(const id of i.messageIds){const m=await p.message(tx,actor,id);if(m.channelId!==c.id||m.subjectVersion!==i.subjectVersion)throw fail('PEER_VERSION','Formal source message version is stale',409);}const identity=await p.who(actor),key=hash([c.id,identity,i.requestKey]),digest=hash(i),old=await tx.get('formal-key',key,false);if(old){if(old.digest!==digest)throw fail('PEER_CONFLICT','Formal key already bound',409);return tx.get('formal',old.id);}const cap=await this.allowed(actor,{capability:i.capability,input:i.input});if(!cap.validateInput(i.input))throw fail('PEER_SCHEMA','Formal capability input invalid',422);const record={...i,id:randomUUID(),actor:identity,state:'admitted',result:null};record.effectKey='peer-formal:'+record.id;await tx.put('formal',record.id,record);await tx.put('formal-key',key,{id:record.id,digest});await tx.audit(c.id,'formal.admitted',identity,{id:record.id,capability:i.capability,messageIds:i.messageIds,inputHash:hash(i.input),effectKey:record.effectKey});fresh=true;return record;});
  if(!fresh)return this.view(actor,r);
  let result;try{result=await this.dispatcher.invoke(r.capability,r.input,{actor,callId:r.effectKey});}catch{await this.finish(r,'unknown',null);return {...await this.view(actor,{...r,state:'unknown'}),errorCode:'PEER_OUTCOME_UNKNOWN'};}await this.finish(r,'confirmed',result);return this.view(actor,{...r,state:'confirmed',result});
 }
 async finish(r,state,result){return this.peer.store.transaction(async tx=>{const current=await tx.get('formal',r.id);if(current.state==='confirmed')return current;current.state=state;current.result=result;await tx.put('formal',r.id,current);await tx.audit(r.channelId,'formal.'+state,r.actor,{id:r.id,effectKey:r.effectKey,resultHash:result===null?null:hash(result)});return current;});}
}
