import {randomUUID,createHash} from 'node:crypto';
import {Notifications} from '../../notifications/service.js';
import {PostgresNotificationStore} from '../../notifications/store.js';
import {validate,checkedIdentity,canonical,hash,same,future,active,viewChannel,fail} from './contracts.js';
export class PeerCollaboration{
 constructor({store,resolveIdentity,restoreActor,authorize,verifyEndpoint,validateContent,readEvidence,resolveDelivery,isEnabled=()=>true,clock=()=>Date.now(),messagesPerMinute=60}){
  if(!store||[resolveIdentity,restoreActor,authorize,verifyEndpoint,validateContent,readEvidence,resolveDelivery,isEnabled,clock].some(f=>typeof f!=='function'))throw Error('Peer storage, identity, policy, binding, content, evidence and delivery ports required');if(!Number.isInteger(messagesPerMinute)||messagesPerMinute<1)throw Error('Positive per-channel message rate required');Object.assign(this,{store,resolveIdentity,restoreActor,authorize,verifyEndpoint,validateContent,readEvidence,resolveDelivery,isEnabled,clock,messagesPerMinute});
  this.notifications=new Notifications({store:new PostgresNotificationStore({pool:store.pool,namespace:store.deliveryNamespace}),resolveScope:actor=>actor.channelId,authorize:async()=>false,resolveDelivery:job=>this.transport(job)});
 }
 async who(actor){return checkedIdentity(await this.resolveIdentity(actor));}
 async permit(actor,action,context={}){if(await this.authorize(actor,{action,...context})!==true)throw fail('PEER_DENIED','Peer operation denied',403);}
 async enabled(){if(await this.isEnabled()!==true)throw fail('PEER_DISABLED','New peer work is disabled',503);}
 async channel(tx,actor,id,{write=false}={}){const c=await tx.get('channel',id);const identity=await this.who(actor);await this.permit(actor,write?'channel.use':'channel.read',{channel:c,identity});if(write){await this.enabled();if(!active(c,this.clock()))throw fail('PEER_CHANNEL_CLOSED','Channel is not active',409);}return c;}
 async endpoint(tx,id,{live=true}={}){const e=await tx.get('endpoint',id);if(live&&(e.status!=='active'||Date.parse(e.validUntil)<=this.clock()))throw fail('PEER_ENDPOINT','Endpoint binding inactive',403);return e;}
 async participant(tx,actor,c){const who=await this.who(actor);for(const id of c.endpointIds){const e=await this.endpoint(tx,id,{live:false});if(same(e.identity,who))return e;}throw fail('PEER_PARTICIPANT','Actor is not a channel participant',403);}
 async grant(tx,c,id,{actor=null,type=null,direction='sendTypes'}={}){const g=await tx.get('grant',id);const e=await this.endpoint(tx,g.endpointId);if(g.channelId!==c.id||c.currentGrants[e.id]!==g.id||!c.endpointIds.includes(e.id)||g.revoked||Date.parse(g.expiresAt)<=this.clock()||g.binding!==e.binding||type&&!g[direction].includes(type))throw fail('PEER_GRANT','Grant is inactive or outside scope',403);if(actor&&!same(e.identity,await this.who(actor)))throw fail('PEER_IDENTITY','Sender binding mismatch',403);if(actor)await this.permit(actor,'grant.use',{channel:c,grant:g,type});return {grant:g,endpoint:e};}
 async evidence(actor,c,refs,recipient=null){for(const ref of refs){const r=await this.readEvidence({actor,channel:c,reference:ref,recipient});if(!r||r.revoked||r.subjectRef!==c.subjectRef||r.subjectVersion!==c.subjectVersion||r.version!==ref.version||Date.parse(r.validUntil)<=this.clock()||!Number.isFinite(Date.parse(r.validUntil))||typeof r.producerRef!=='string'||!r.producerRef||!Number.isFinite(Date.parse(r.issuedAt))||Date.parse(r.issuedAt)>this.clock()||typeof r.content!=='string'||Buffer.byteLength(r.content)>8*1024*1024||createHash('sha256').update(r.content).digest('hex')!==ref.hash)throw fail('PEER_EVIDENCE','Evidence unavailable, unauthorized, expired or changed',403);}}
 async run(actor,operation,input){input=validate(operation,input);const identity=await this.who(actor);try{return await this.store.transaction(tx=>this.execute(tx,actor,identity,operation,input));}catch(e){await this.store.transaction(tx=>tx.audit('', 'operation.rejected',identity,{operation,code:e.code??'PEER_ERROR',inputHash:hash(input)})).catch(()=>{});throw e;}}
 async execute(tx,actor,identity,op,i){
  if(op==='endpoint.register'){await this.enabled();await this.permit(actor,op,{input:i});const b=await this.verifyEndpoint(actor,i);const bindingIdentity=checkedIdentity(b?.identity);const validUntil=future(b.validUntil,this.clock());if(typeof b.verificationRef!=='string'||!b.verificationRef||b.endpointRef!==i.endpointRef||b.protocol!==i.protocol)throw fail('PEER_BINDING','Verified endpoint reference and protocol required',403);const binding=hash({identity:bindingIdentity,endpointRef:i.endpointRef,protocol:i.protocol,verificationRef:b.verificationRef,validUntil});const old=await tx.get('endpoint',i.id,false);if(old){if(old.binding!==binding)throw fail('PEER_CONFLICT','Endpoint ID has a different immutable binding',409);return old;}const e={...i,identity:bindingIdentity,verificationRef:b.verificationRef,validUntil,binding,status:'active'};await tx.put('endpoint',i.id,e);await tx.audit('',op,identity,{endpointId:i.id,binding});return e;}
  if(op==='endpoint.status'){await this.permit(actor,op,{input:i});const e=await this.endpoint(tx,i.id,{live:false});if(e.status==='revoked'&&i.status!=='revoked')throw fail('PEER_ENDPOINT','Revoked binding cannot reactivate',409);e.status=i.status;await tx.put('endpoint',i.id,e);await tx.audit('',op,identity,{id:i.id,status:i.status});return e;}
  if(op==='channel.create'){await this.enabled();await this.permit(actor,op,{input:i});const expiresAt=future(i.expiresAt,this.clock());const endpoints=await Promise.all(i.endpointIds.map(id=>this.endpoint(tx,id)));if(new Set(endpoints.map(e=>canonical([e.identity.tenantId,e.identity.principalId]))).size<2)throw fail('PEER_PARTICIPANT','Independent principals required');const digest=hash(i),old=await tx.get('channel',i.id,false);if(old){if(old.digest!==digest)throw fail('PEER_CONFLICT','Channel ID already bound',409);return viewChannel(old,this.clock());}const c={...i,expiresAt,digest,state:'requested',sequence:0,revision:1,currentGrants:{}};await tx.put('channel',c.id,c);await tx.audit(c.id,op,identity,{subjectRef:c.subjectRef});return c;}
  if(op==='channel.transition'||op==='channel.subject'){const c=await tx.get('channel',i.id);await this.permit(actor,op,{channel:c,input:i});if(c.revision!==i.expectedRevision)throw fail('PEER_VERSION','Channel revision changed',409);if(Date.parse(c.expiresAt)<=this.clock()||['closed','expired'].includes(c.state))throw fail('PEER_CHANNEL_CLOSED','Channel cannot reopen',409);if(op==='channel.subject'){await this.enabled();c.subjectVersion=i.subjectVersion;}else{const transitions={requested:['active','closing','closed'],active:['suspended','closing'],suspended:['active','closing','closed'],closing:['closed']};if(!transitions[c.state]?.includes(i.state))throw fail('PEER_STATE','Invalid channel transition',409);if(i.state==='active')await this.enabled();c.state=i.state;}c.revision++;await tx.put('channel',c.id,c);await tx.audit(c.id,op,identity,{state:c.state,revision:c.revision,subjectVersion:c.subjectVersion});return viewChannel(c,this.clock());}
  if(op==='channel.get'){const c=await this.channel(tx,actor,i.id);await this.participantOrController(tx,actor,c);return viewChannel(c,this.clock());}
  if(op==='channel.audit'){const c=await this.channel(tx,actor,i.id);await this.participantOrController(tx,actor,c);await this.permit(actor,op,{channel:c});return {items:await tx.history(c.id,i.after??0,i.limit??50)};}
  if(op==='grant.issue'){await this.enabled();const c=await tx.get('channel',i.channelId);await this.permit(actor,op,{channel:c,input:i});if(['closing','closed','expired'].includes(c.state)||Date.parse(c.expiresAt)<=this.clock())throw fail('PEER_CHANNEL_CLOSED','Channel cannot issue grants',409);const e=await this.endpoint(tx,i.endpointId);if(!c.endpointIds.includes(e.id))throw fail('PEER_PARTICIPANT','Endpoint outside channel',403);const expiresAt=future(i.expiresAt,this.clock());if(Date.parse(expiresAt)>Math.min(Date.parse(c.expiresAt),Date.parse(e.validUntil)))throw fail('PEER_EXPIRY','Grant exceeds channel or binding lifetime');const digest=hash(i),old=await tx.get('grant',i.id,false);if(old){if(old.digest!==digest)throw fail('PEER_CONFLICT','Grant ID already bound',409);return old;}const g={...i,digest,binding:e.binding,expiresAt,revoked:false};await tx.put('grant',g.id,g);c.currentGrants[e.id]=g.id;c.revision++;await tx.put('channel',c.id,c);await tx.audit(c.id,op,identity,{grantId:g.id,endpointId:e.id});return g;}
  if(op==='grant.revoke'){const g=await tx.get('grant',i.id),c=await tx.get('channel',g.channelId);await this.permit(actor,op,{channel:c,grant:g});g.revoked=true;await tx.put('grant',g.id,g);await tx.audit(c.id,op,identity,{grantId:g.id});return g;}
  if(op==='message.lookup'){const c=await this.channel(tx,actor,i.channelId),e=await this.participant(tx,actor,c);const record=await tx.get('message-key',hash([c.id,e.id,i.requestKey]),false);return record?{status:'recorded',receipt:await this.receipt(tx,await tx.get('message',record.id))}:{status:'unknown'};}
  if(op==='message.send')return this.send(tx,actor,i);
  if(op==='message.inbox'){const c=await this.channel(tx,actor,i.channelId),e=await this.participant(tx,actor,c);const rows=await tx.list('message',c.id,(i.after??0)+1,i.limit??50);const items=[];for(const m of rows)if(m.senderEndpointId===e.id||m.recipientEndpointIds.includes(e.id))items.push(await this.message(tx,actor,m.id));return {items,nextSequence:rows.at(-1)?.sequence??i.after??0};}
  if(op==='message.get'){const m=await this.message(tx,actor,i.id);return {...m,receipt:await this.receipt(tx,m)};}
  if(op==='message.ack'){const m=await this.message(tx,actor,i.id),c=await tx.get('channel',m.channelId),e=await this.participant(tx,actor,c);if(e.id!==i.recipientEndpointId||!m.recipientEndpointIds.includes(e.id))throw fail('PEER_IDENTITY','Only the bound recipient can acknowledge',403);await this.permit(actor,op,{channel:c,message:m});if(!m.acknowledged.includes(e.id)){m.acknowledged.push(e.id);await tx.put('message',m.id,m);await tx.audit(c.id,op,identity,{messageId:m.id,endpointId:e.id});}return this.receipt(tx,m);}
  throw fail('PEER_OPERATION','Operation requires its separate service');
 }
 async participantOrController(tx,actor,c){try{return await this.participant(tx,actor,c);}catch(e){if(e.code!=='PEER_PARTICIPANT')throw e;await this.permit(actor,'channel.inspect',{channel:c});return null;}}
 async send(tx,actor,i){const c=await this.channel(tx,actor,i.channelId,{write:true});await this.permit(actor,'message.send',{channel:c,input:i});const {endpoint:sender}=await this.grant(tx,c,i.grantId,{actor,type:i.type});const requestId=hash([c.id,sender.id,i.requestKey]),digest=hash(i);const old=await tx.get('message-key',requestId,false);if(old){if(old.digest!==digest)throw fail('PEER_CONFLICT','Message key already bound',409);return this.receipt(tx,await tx.get('message',old.id));}if(i.subjectVersion!==c.subjectVersion||i.expectedSequence!==c.sequence)throw fail('PEER_VERSION','Refresh channel subject/version and sequence',409);const window=Math.floor(this.clock()/60000);if(c.rateWindow!==window){c.rateWindow=window;c.rateCount=0;}if((c.rateCount??0)>=this.messagesPerMinute)throw fail('PEER_RATE','Channel message rate exceeded',429);c.rateCount=(c.rateCount??0)+1;if(c.sequence>=c.maxMessages)throw fail('PEER_LIMIT','Channel message ceiling reached',429);if(i.recipientEndpointIds.includes(sender.id))throw fail('PEER_PARTICIPANT','Peer message cannot target its sender');if(i.replyTo){const parent=await tx.get('message',i.replyTo);if(parent.subjectVersion!==i.subjectVersion)throw fail('PEER_VERSION','Reply refers to an older subject version',409);if(parent.channelId!==c.id||(!parent.recipientEndpointIds.includes(sender.id)&&parent.senderEndpointId!==sender.id))throw fail('PEER_SCOPE','Reply target outside scope',403);}
 const refs=i.references??[];if(!c.retainBody&&i.content!=null)throw fail('PEER_RETENTION','Channel permits references only',403);if(await this.validateContent({actor,channel:c,type:i.type,schemaVersion:i.schemaVersion,content:i.content??null})!==true)throw fail('PEER_SCHEMA','Message content schema rejected',422);const recipients=[];for(const endpointId of i.recipientEndpointIds){const grantId=c.currentGrants[endpointId];if(!grantId)throw fail('PEER_GRANT','Recipient has no channel grant',403);const r=await this.grant(tx,c,grantId,{type:i.type,direction:'receiveTypes'});await this.evidence(actor,c,refs,r.endpoint.identity);recipients.push({endpointId,grantId,binding:r.endpoint.binding});}
 const m={...i,id:randomUUID(),protocolVersion:'iaic.peer.v1',channelId:c.id,subjectRef:c.subjectRef,sequence:++c.sequence,senderEndpointId:sender.id,sender:sender.identity,senderBinding:sender.binding,recipients,references:refs,content:i.content??null,acknowledged:[],createdAt:new Date(this.clock()).toISOString(),expiresAt:c.expiresAt};delete m.expectedSequence;await tx.put('channel',c.id,c);await tx.put('message',m.id,m);await tx.put('message-key',requestId,{id:m.id,digest});for(const recipient of recipients)await tx.outbox.enqueue(c.id,{requestKey:m.id+':'+recipient.endpointId,recipientId:recipient.endpointId,channel:'peer',message:{id:m.id},source:{channelId:c.id,sequence:m.sequence}});await tx.audit(c.id,'message.accepted',sender.identity,{id:m.id,sequence:m.sequence,contentHash:hash(m.content),references:refs});return this.receipt(tx,m);
 }
 async message(tx,actor,id){const m=await tx.get('message',id),c=await this.channel(tx,actor,m.channelId),e=await this.participant(tx,actor,c);if(e.id!==m.senderEndpointId&&!m.recipientEndpointIds.includes(e.id))throw fail('PEER_SCOPE','Message is not addressed to actor',403);await this.permit(actor,'message.read',{channel:c,message:m});await this.evidence(actor,{...c,subjectVersion:m.subjectVersion},m.references);await tx.audit(c.id,'message.read',await this.who(actor),{messageId:m.id});return m;}
 async receipt(tx,m){const deliveries=[];for(const endpointId of m.recipientEndpointIds){const job=await tx.outbox.get(m.channelId,m.id+':'+endpointId);deliveries.push({endpointId,state:m.acknowledged.includes(endpointId)?'application_acknowledged':({pending:'queued',sending:'unknown',delivered:job.result?.milestone==='sent'?'sent':'delivered',failed:'failed',unknown:'unknown',cancelled:'failed'})[job.state],attempt:job.attempt});}return {id:m.id,channelId:m.channelId,sequence:m.sequence,state:'accepted',deliveries};}
 async transport(job){const data=await this.store.transaction(async tx=>{const m=await tx.get('message',job.message.id),c=await tx.get('channel',m.channelId),e=await this.endpoint(tx,job.recipientId,{live:false});const recipient=m.recipients.find(r=>r.endpointId===e.id);if(!recipient||recipient.binding!==e.binding)throw fail('PEER_BINDING','Original recipient binding changed',403);return {message:m,channel:c,endpoint:e};});const transport=await this.resolveDelivery(data);if(typeof transport?.send!=='function')return {allowed:false};return {allowed:true,send:async({idempotencyKey,signal})=>{const allowed=await this.store.transaction(async tx=>{try{const actor=await this.restoreActor(data.message.sender);const c=await this.channel(tx,actor,data.channel.id,{write:true});if(c.subjectVersion!==data.message.subjectVersion)throw fail('PEER_VERSION','Queued message subject changed',409);await this.grant(tx,c,data.message.grantId,{actor,type:data.message.type});await this.grant(tx,c,data.message.recipients.find(r=>r.endpointId===job.recipientId).grantId,{type:data.message.type,direction:'receiveTypes'});await this.evidence(actor,c,data.message.references,data.endpoint.identity);await this.permit(actor,'message.deliver',{channel:c,message:data.message});await tx.audit(c.id,'delivery.admitted',await this.who(actor),{messageId:data.message.id,recipient:job.recipientId,attempt:job.attempt});return true;}catch(e){if(e.statusCode>=500)throw e;return false;}});if(!allowed)return {status:'not_sent',reason:'current-policy-denied-before-send'};return this.deliveryResult(await transport.send({idempotencyKey,envelope:data.message,signal}));},...(typeof transport.query==='function'?{query:async({idempotencyKey})=>this.deliveryResult(await transport.query({idempotencyKey}))}:{})};}
 deliveryResult(r){if(r?.status==='delivered'){if(!['sent','delivered'].includes(r.milestone)||typeof r.receiptRef!=='string'||!r.receiptRef||r.receiptRef.length>500)return {status:'unknown',reason:'endpoint-milestone-evidence-missing'};return {status:'delivered',milestone:r.milestone,receiptRef:r.receiptRef};}return {status:r?.status==='not_sent'?'not_sent':'unknown'};}

 async tick(options){return this.notifications.tick(options);}
 async delivery(actor,operation,input){const i=validate(operation,input);const context=await this.store.transaction(async tx=>{const m=await this.message(tx,actor,i.id);if(!m.recipientEndpointIds.includes(i.recipientEndpointId))throw fail('PEER_SCOPE','Recipient outside message',403);const c=await tx.get('channel',m.channelId);await this.permit(actor,operation,{channel:c,message:m});const key=m.id+':'+i.recipientEndpointId;if(operation==='delivery.retry'){await this.channel(tx,actor,c.id,{write:true});await this.grant(tx,c,m.grantId,{actor,type:m.type});const history=await tx.outbox.history(c.id,key);if(history.length>=c.maxAttempts)throw fail('PEER_RETRY_EXHAUSTED','Escalate to the configured human owner',409);}return {channelId:c.id,requestKey:key};});
 // A per-call private facade keeps concurrent callers from sharing authority.
 const token={channelId:context.channelId};const service=new Notifications({store:this.notifications.store,resolveScope:()=>context.channelId,authorize:a=>a===token,resolveDelivery:job=>this.transport(job)});await service[operation==='delivery.retry'?'retry':'reconcile'](token,{requestKey:context.requestKey});return this.store.transaction(async tx=>this.receipt(tx,await tx.get('message',i.id)));}
}
