import {validate,hash,future,fail,same} from './contracts.js';
export class PeerInformationRequests{
 constructor({peer}){this.peer=peer;}
 async run(actor,operation,input){if(!operation.startsWith('information.'))throw fail('PEER_OPERATION','Unknown operation');const p=this.peer,i=validate(operation,input);return p.store.transaction(async tx=>{
  if(operation==='information.create'){const dueAt=future(i.dueAt,p.clock());const wire={channelId:i.channelId,grantId:i.grantId,requestKey:i.requestKey,recipientEndpointIds:[i.targetEndpointId],subjectVersion:i.subjectVersion,expectedSequence:i.expectedSequence,type:'information.request',schemaVersion:'iaic.information.v1',content:{fields:i.fields,reason:i.reason,acceptedSchema:i.acceptedSchema,dueAt},references:[]};const receipt=await p.send(tx,actor,wire);let r=await tx.get('information',receipt.id,false);if(!r){const c=await tx.get('channel',i.channelId);if(Date.parse(dueAt)>Date.parse(c.expiresAt))throw fail('PEER_EXPIRY','Information request exceeds channel lifetime');r={id:receipt.id,channelId:i.channelId,subjectVersion:i.subjectVersion,targetEndpointId:i.targetEndpointId,fields:i.fields,acceptedSchema:i.acceptedSchema,dueAt,status:'open',requester:await p.who(actor),responseId:null};await tx.put('information',r.id,r);await tx.audit(r.channelId,operation,r.requester,{id:r.id,fields:r.fields});}return {...r,receipt};}
  const r=await tx.get('information',i.id);await p.message(tx,actor,r.id);const expired=Date.parse(r.dueAt)<=p.clock();if(operation==='information.get')return {...r,status:r.status==='open'&&expired?'expired':r.status};
  const c=await p.channel(tx,actor,r.channelId,{write:true}),e=await p.participant(tx,actor,c);if(e.id!==r.targetEndpointId)throw fail('PEER_IDENTITY','Only the requested principal can respond',403);const binding=hash({actor:await p.who(actor),input:i});if(r.responseId){if(r.responseDigest!==binding)throw fail('PEER_CONFLICT','Information request already resolved',409);return {...r,receipt:await p.receipt(tx,await tx.get('message',r.responseId))};}if(expired)throw fail('PEER_EXPIRY','Information request expired',409);const values=i.values??{};if(Object.keys(values).some(k=>!r.fields.includes(k))||(i.status==='answered'&&r.fields.some(k=>!Object.hasOwn(values,k)))||(i.status!=='answered'&&Object.keys(values).length))throw fail('PEER_DISCLOSURE','Response must contain only requested fields',422);
  if(i.status==='answered'&&await p.validateContent({actor,channel:c,type:'information.answer',schemaVersion:r.acceptedSchema,content:values})!==true)throw fail('PEER_SCHEMA','Information answer schema rejected',422);
  const receipt=await p.send(tx,actor,{channelId:c.id,grantId:i.grantId,requestKey:i.requestKey,recipientEndpointIds:[(await tx.get('message',r.id)).senderEndpointId],subjectVersion:r.subjectVersion,expectedSequence:i.expectedSequence,type:'information.response',schemaVersion:'iaic.information.v1',content:{requirementId:r.id,status:i.status,values,reason:i.reason??null},replyTo:r.id,references:[]});r.status=i.status;r.responseId=receipt.id;r.responseDigest=binding;await tx.put('information',r.id,r);await tx.audit(c.id,operation,await p.who(actor),{id:r.id,responseId:r.responseId,status:r.status});return {...r,receipt};
 });}
}
