import test from 'node:test';
import assert from 'node:assert/strict';
import {CapabilityDispatcher,defineCapability,createCapabilityA2AHandler} from '@immedi/iaic-core';
async function fixture(){let calls=0;const dispatcher=new CapabilityDispatcher({capabilities:[defineCapability({name:'echo.read',description:'Read input',effect:'read',input:{type:'string'},output:{type:'string'},authorize:a=>a.subjectId==='owner',implementation:{kind:'function',execute:input=>{calls++;return input;}}})]});const handler=await createCapabilityA2AHandler({dispatcher,capability:'echo.read',url:'https://example.test/rpc',resolveAccess:()=>({actor:{subjectId:'owner'},capabilities:['echo.read']})});const rpc=async(method,params,version='1.0')=>(await handler(new Request('https://example.test/rpc',{method:'POST',headers:{'content-type':'application/json','a2a-version':version},body:JSON.stringify({jsonrpc:'2.0',id:7,method,params})}))).json();return {rpc,calls:()=>calls};}
test('A2A wire validates versions and unsupported streaming without dispatching work',async()=>{const {rpc,calls}=await fixture();assert.ok((await rpc('GetTask',{id:'missing'},'0.3')).error);assert.ok((await rpc('SendStreamingMessage',{message:{messageId:'m',role:'ROLE_USER',parts:[{data:'hello'}]}})).error);assert.equal(calls(),0);});
test('A2A direct messages preserve shared input validation and exact structured results',async()=>{const {rpc,calls}=await fixture();const send=data=>rpc('SendMessage',{message:{messageId:'m',role:'ROLE_USER',parts:[{data}]}});assert.ok((await send(42)).error);assert.equal(calls(),0);const result=await send('hello');assert.equal(result.result.message.parts[0].data,'hello');assert.equal(result.result.message.role,'ROLE_AGENT');assert.equal(calls(),1);});
test('Outbound A2A keeps lost write responses unknown and does not retry or bypass authorization',async()=>{
 const {importA2ACapabilities}=await import('@immedi/iaic-core');let sent=0;
 const capabilities=await importA2ACapabilities({agentCard:{name:'fixture',supportedInterfaces:[{url:'https://example.test/rpc',protocolBinding:'JSONRPC',protocolVersion:'1.0'}]},prefix:'remote',authorize:a=>a.subjectId==='owner',resolveHeaders:()=>({authorization:'Bearer fixture'}),fetch:async(url,options)=>{sent++;assert.equal(options.redirect,'error');assert.equal(new Headers(options.headers).get('authorization'),'Bearer fixture');assert.ok(options.signal);throw new Error('response lost');}});
 const dispatcher=new CapabilityDispatcher({capabilities});
 await assert.rejects(dispatcher.invoke('remote.send',{}, {actor:{subjectId:'other'},callId:'stable'}),{statusCode:403});assert.equal(sent,0);
 await assert.rejects(dispatcher.invoke('remote.send',{}, {actor:{subjectId:'owner'},callId:'stable'}),e=>e.outcomeUnknown===true&&e.requestKey==='stable');assert.equal(sent,1);
 assert.equal(capabilities.find(c=>c.name==='remote.send').retry,'never-replay');
});
