import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {PostgresPaymentStore,Payments} from '@immedi/iaic-core';
async function fixture(run){const connectionString=process.env.SUBMISSION_TEST_DATABASE_URL;if(!connectionString)throw new Error('Isolated PostgreSQL required');const admin=new Pool({connectionString}),schema='payments_test_'+randomUUID().replaceAll('-','');await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({connectionString,options:`-c search_path=${schema}`});try{const store=new PostgresPaymentStore({pool,namespace:'test'});await store.initialize();await run(store);}finally{await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}}
test('Monetary invoices are scoped, immutable and never use floating point',async()=>fixture(async store=>{const b=await store.issue('a',{sourceId:'quote',currency:'USD',amount:'999999999999999999999999999999'});assert.equal(b.amount,'999999999999999999999999999999');await assert.rejects(store.issue('a',{sourceId:'quote',currency:'USD',amount:'2'}),{statusCode:409});await assert.rejects(store.read('b',b.id),{statusCode:404});await assert.rejects(store.issue('a',{sourceId:'other',currency:'USD',amount:1}));}));
test('Dispatch claim survives reconstruction and cancellation releases only undispatched intents',async()=>fixture(async store=>{const b=await store.issue('a',{sourceId:'quote',currency:'USD',amount:'100'});const op=await store.prepare('a',{invoiceId:b.id,requestKey:'first',kind:'charge'});await store.cancel('a',op.id);const next=await store.prepare('a',{invoiceId:b.id,requestKey:'second',kind:'charge'});assert.ok(await store.claim('a',next.id));assert.equal(await store.claim('a',next.id),null);await assert.rejects(store.cancel('a',next.id),{statusCode:409});await assert.rejects(store.prepare('a',{invoiceId:b.id,requestKey:'third',kind:'charge'}),{statusCode:409});await assert.rejects(store.record('a',next.id,{operationId:next.id,status:'succeeded',amount:'101',currency:'USD',providerRef:'p'}),{statusCode:409});}));
test('Mismatched provider evidence and timeouts remain unknown without automatic replay',async()=>fixture(async store=>{let calls=0;const provider={charge:async op=>{calls++;return {operationId:op.id,status:'succeeded',amount:'999',currency:'USD',providerRef:'p'};},refund:async()=>{},query:async()=>new Promise(()=>{})};const service=new Payments({store,provider,resolveScope:()=> 'a',authorize:()=>true,resolveInvoice:sourceId=>({sourceId,scopeId:'a',confirmed:true,currency:'USD',amount:'100'}),timeoutMs:20});const b=await service.issue({}, {sourceId:'quote'});const op=await service.charge({}, {invoiceId:b.id,requestKey:'same'});assert.equal(op.state,'unknown');assert.equal((await service.reconcile({}, {id:op.id})).state,'unknown');await service.charge({}, {invoiceId:b.id,requestKey:'same'});assert.equal(calls,1);assert.equal((await service.reconcile({}, {id:op.id},{signal:AbortSignal.abort()})).state,'unknown');}));
test('HTTP payment adapter binds the original operation key and reconciles without posting again',async()=>{
 const {createHttpPaymentProvider}=await import('@immedi/iaic-core');const seen=[];const op={id:randomUUID(),amount:'100',currency:'USD'};
 const provider=createHttpPaymentProvider({baseUrl:'https://payments.test/v1/',idempotencyHeader:'Idempotency-Key',resolveHeaders:()=>({authorization:'Bearer fixture'}),bindings:{charge:{request:o=>({path:'charges',body:o}),project:x=>x},refund:{request:o=>({path:'refunds',body:o}),project:x=>x},query:{request:o=>({path:'operations/'+o.id}),project:x=>x}},fetch:async(url,options)=>{seen.push({url:String(url),method:options.method,key:new Headers(options.headers).get('idempotency-key')});return Response.json({...op,operationId:op.id,status:'succeeded',providerRef:'fixture-ref'});}});
 assert.equal((await provider.charge(op)).operationId,op.id);assert.equal((await provider.query(op)).providerRef,'fixture-ref');assert.deepEqual(seen.map(x=>x.method),['POST','GET']);assert.equal(seen[0].key,op.id);assert.equal(seen[1].key,null);
});
