import {OpenAIProvider} from '@immedi/iaic-core/agent/openai-provider.js';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {spawn} from 'node:child_process';import {once} from 'node:events';import {Pool} from 'pg';
import {PostgresModelCapacity,capacityModel,ModelCapacityReconciliation,TokenLedger,meteredModel,AgentRuntime,TaskStore,ContextAssembler,CapabilityDispatcher,defineCapability} from '@immedi/iaic-core';
async function fixture(run){const connectionString=process.env.SUBMISSION_TEST_DATABASE_URL;assert.ok(connectionString);const schema='capacity_'+randomUUID().replaceAll('-',''),admin=new Pool({connectionString});await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({connectionString,options:`-c search_path=${schema}`});try{const capacity=new PostgresModelCapacity({pool,namespace:'provider-account',maxConcurrent:1});await capacity.initialize();await run({pool,capacity,schema});}finally{await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}}
const request=(taskId,turn=1)=>({billingContext:{taskId,turn}});
test('Shared capacity serializes admissions, persists original turns and preserves mismatched pool policy',()=>fixture(async({pool,capacity})=>{
 const results=await Promise.allSettled([capacity.admit({taskId:'a',turn:1}),new PostgresModelCapacity({pool,namespace:'provider-account',maxConcurrent:1}).admit({taskId:'b',turn:1})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'MODEL_CAPACITY_BUSY');
 const receipt=results.find(r=>r.status==='fulfilled').value;await capacity.release(receipt.id,{kind:'fixture-finished'});await assert.rejects(capacity.admit({taskId:receipt.task_id,turn:1}),{code:'MODEL_TURN_ALREADY_ADMITTED'});
 await assert.rejects(new PostgresModelCapacity({pool,namespace:'provider-account',maxConcurrent:2}).initialize(),{statusCode:409});assert.equal((await capacity.pending()).items.length,0);
}));
test('Busy admission has no platform debit; confirmed completion releases capacity while uncertain provider errors retain it',()=>fixture(async({pool,capacity})=>{
 const ledger=new TokenLedger({pool});await ledger.initialize();const scope={applicationId:'app',subjectId:'user'};await ledger.grant(scope,{reference:'fixture',amount:100,evidence:{fixture:true}});let calls=0;
 const model={name:'fixture',next:async()=>{calls++;return {type:'finish',result:{done:true},usage:{inputTokens:2,outputTokens:1}};}};
 const wrapped=meteredModel({model:capacityModel({model,capacity}),ledger,scope,policy:{maximum:20,price:{revision:'p1',input:2,cachedInput:1,output:3}}});
 const occupied=await capacity.admit({taskId:'other',turn:1});await assert.rejects(wrapped.next(request('busy')),error=>error.code==='MODEL_CAPACITY_BUSY'&&error.providerNotCalled);assert.equal(calls,0);assert.equal((await ledger.balance(scope)).available,'100');assert.equal((await ledger.pending(scope)).length,0);
 await capacity.release(occupied.id,{kind:'fixture-finished'});const response=await wrapped.next(request('success'));assert.equal(response.capacity.releaseConfirmed,true);assert.equal((await capacity.pending()).items.length,0);assert.equal((await ledger.balance(scope)).available,'93');
 const uncertain=capacityModel({capacity,model:{name:'fixture',next:async()=>{throw new Error('Transport lost');}}});await assert.rejects(uncertain.next(request('unknown')),/Transport lost/);assert.equal((await capacity.pending()).items.length,1);
}));
test('SIGKILL retains capacity until a trusted original-request terminal receipt authorizes release',()=>fixture(async({pool,capacity,schema})=>{
 const code=`import {Pool} from 'pg';import {PostgresModelCapacity} from '@immedi/iaic-core';const pool=new Pool({connectionString:process.env.SUBMISSION_TEST_DATABASE_URL,options:'-c search_path='+process.env.IAIC_CAPACITY_SCHEMA});const c=new PostgresModelCapacity({pool,namespace:'provider-account',maxConcurrent:1});const r=await c.admit({taskId:'crashed',turn:1});process.send(r.id);setInterval(()=>{},1000);`;
 const child=spawn(process.execPath,['--input-type=module','-e',code],{env:{...process.env,IAIC_CAPACITY_SCHEMA:schema},stdio:['ignore','ignore','pipe','ipc']});let id;
 try{[id]=await once(child,'message',{signal:AbortSignal.timeout(10000)});const exited=once(child,'exit');child.kill('SIGKILL');assert.equal((await exited)[1],'SIGKILL');}finally{if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');}
 const restored=new PostgresModelCapacity({pool,namespace:'provider-account',maxConcurrent:1});assert.equal((await restored.get(id)).state,'active');await assert.rejects(restored.admit({taskId:'later',turn:1}),{code:'MODEL_CAPACITY_BUSY'});
 let confirmed=false,allowed=true;const reconcile=new ModelCapacityReconciliation({capacity:restored,authorize:()=>allowed,resolveSource:(_a,{reservationId,sourceId})=>({reservationId,sourceId,namespace:'provider-account',confirmedTerminal:confirmed,outcome:'finished'})});
 await assert.rejects(reconcile.resolve({}, {reservationId:id,sourceId:'provider-receipt'}),{statusCode:409});confirmed=true;allowed=false;await assert.rejects(reconcile.resolve({}, {reservationId:id,sourceId:'provider-receipt'}),{statusCode:403});allowed=true;
 assert.equal((await reconcile.resolve({}, {reservationId:id,sourceId:'provider-receipt'})).state,'released');assert.equal((await restored.admit({taskId:'later',turn:1})).state,'active');
}));

test('Completed invalid provider output releases capacity so the same Runtime can request a corrected action',()=>fixture(async({pool,capacity})=>{
 const ledger=new TokenLedger({pool});await ledger.initialize();const actor={subjectId:'user',scopeId:'app'},scope={applicationId:'app',subjectId:'user'};await ledger.grant(scope,{reference:'fixture',amount:100,evidence:{fixture:true}});let calls=0;
 const provider=new OpenAIProvider({apiKey:'fixture-not-a-key',model:'fixture',fetchImpl:async()=>{calls++;return new Response(JSON.stringify({id:'response-'+calls,status:'completed',usage:{input_tokens:3,output_tokens:2},output:[{type:'function_call',name:calls===1?'not_configured':'iaic_finish',arguments:JSON.stringify(calls===1?{}:{result:{done:true}})}]}));}});
 const model=meteredModel({model:capacityModel({model:provider,capacity}),ledger,scope,policy:{maximum:20,price:{revision:'fixture',input:1,cachedInput:1,output:2}}});
 const agent=defineCapability({name:'work',description:'Correct an invalid action',input:{type:'object'},output:{type:'object'},effect:'read',authorize:()=>true,implementation:{kind:'agent',instructions:'Finish correctly',tools:[],verify:(_input,result)=>result.done===true}});
 const store=new TaskStore({pool}),dispatcher=new CapabilityDispatcher({capabilities:[agent]}),runtime=new AgentRuntime({store,dispatcher,model,context:new ContextAssembler({}),version:'fixture',maxTurns:3,rateLimitDelayMs:0});dispatcher.tasks=runtime;
 try{await runtime.initialize();const task=await runtime.create({actor,capability:agent,input:{goal:'Complete with a corrected action'},idempotencyKey:'correct'});const outcome=await runtime.tick();assert.equal(outcome.status,'succeeded',outcome.error);assert.equal(calls,2);assert.equal((await capacity.pending()).items.length,0);assert.equal((await ledger.balance(scope)).available,'86');assert.equal((await ledger.pending(scope)).length,0);assert.ok((await store.history(actor,task.id)).events.some(e=>e.kind==='feedback'));}finally{await runtime.stop();}
}));
