import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {Pool} from 'pg';
import {PostgresWorkspaceStore,AssistantWorkspace,TaskStore,AgentRuntime,ContextAssembler,CapabilityDispatcher,createAgentTaskCapabilities} from '@immedi/iaic-core';
const url=process.env.SUBMISSION_TEST_DATABASE_URL,actor={scopeId:'workspace-fixture',subjectId:'owner'},scope={applicationId:'fixture',assistantId:'assistant',subjectId:'owner'};
async function fixture(run){const schema='workspace_preflight_'+randomUUID().replaceAll('-',''),admin=new Pool({connectionString:url});await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({connectionString:url,options:`-c search_path=${schema}`});let runtime;try{const store=new PostgresWorkspaceStore({pool});await store.initialize();const workspace=new AssistantWorkspace({store,resolveScope:async(a,access)=>{assert.equal(access.access,['read','list'].includes(access.operation)?'read':'write');if(a.subjectId!==actor.subjectId)throw Object.assign(new Error('Denied'),{statusCode:403});return scope;},sourceFor:()=>({kind:'fixture'})}),capabilities=createAgentTaskCapabilities({memory:{},workspace,authorize:()=>true,verifyOutcome:()=>true}),dispatcher=new CapabilityDispatcher({capabilities});await run({pool,store,workspace,dispatcher,setRuntime:value=>{runtime=value;}});}finally{await runtime?.stop();await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}}
test('Stale Workspace create becomes correctable feedback and the Agent can read back and finish',{skip:!url},async()=>fixture(async({pool,workspace,dispatcher,setRuntime})=>{
 let turn=0;const write={path:'result.json',content:'{"value":42}',mediaType:'application/json',expectedRevision:0};
 const runtime=new AgentRuntime({store:new TaskStore({pool}),dispatcher,version:'fixture',context:new ContextAssembler({skillRoot:'/tmp'}),model:{name:'fixture',next:async()=>{turn++;if(turn<=2)return {type:'call',name:'my_write_workspace',input:write};if(turn===3)return {type:'call',name:'my_read_workspace',input:{path:write.path}};return {type:'finish',result:{summary:'Verified',artifacts:[(await workspace.read(actor,{path:write.path})).reference]}};}}});setRuntime(runtime);dispatcher.tasks=runtime;await runtime.initialize();
 const task=await dispatcher.invoke('assistant.run',{goal:'Prepare and verify result',allowedTools:['my_write_workspace','my_read_workspace']},{actor,callId:'task'});assert.equal((await runtime.tick()).status,'succeeded');
 const history=await runtime.store.history(actor,task.id);assert.deepEqual(history.calls.map(c=>c.status),['succeeded','failed','succeeded']);assert.equal((await workspace.read(actor,{path:write.path})).reference.revision,1);assert.equal(history.events.filter(e=>e.kind==='feedback'&&e.data.error.includes('preflight')).length,1);
}));
test('Workspace preflight checks current write scope, revision and deleted heads',{skip:!url},async()=>fixture(async({workspace,dispatcher})=>{
 const input={path:'draft',content:'draft',expectedRevision:0};assert.equal(await workspace.preflightWrite(actor,input),true);await workspace.write(actor,input);assert.equal(await workspace.preflightWrite(actor,input),false);assert.equal(await workspace.preflightWrite(actor,{...input,expectedRevision:1}),true);
 await assert.rejects(workspace.preflightWrite({...actor,subjectId:'other'},input),{statusCode:403});await workspace.remove(actor,{path:'draft',expectedRevision:1});assert.equal(await workspace.preflightWrite(actor,input),false);
 await assert.rejects(dispatcher.invoke('my_write_workspace',input,{actor,callId:'stale'}),error=>error.preflightRejected===true&&error.outcomeUnknown!==true);
}));
test('A race after successful preflight still preserves write uncertainty',{skip:!url},async()=>fixture(async({store,dispatcher})=>{
 const original=store.canWrite.bind(store);store.canWrite=async(s,input)=>{const allowed=await original(s,input);if(allowed)await store.write(s,{...input,content:'concurrent',source:{kind:'fixture'}});return allowed;};
 await assert.rejects(dispatcher.invoke('my_write_workspace',{path:'race',content:'requested',expectedRevision:0},{actor,callId:'race'}),error=>error.statusCode===409&&error.outcomeUnknown===true);
 assert.equal((await store.read(scope,{path:'race'})).content,'concurrent');
}));
