import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {Pool} from 'pg';
import {EventStore,AssistantEvents,EventTriggers,triggerRouter,DeferredTaskStore,DeferredTasks} from '@immedi/iaic-core';
const admin=new Pool({connectionString:process.env.DATABASE_URL}),schema='event_example_'+randomUUID().replaceAll('-','');await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({connectionString:process.env.DATABASE_URL,options:`-c search_path=${schema}`});
try{
 const scope={applicationId:'neutral',assistantId:'helper',subjectId:'reader'},store=new EventStore({pool});await store.initialize();const events=new AssistantEvents({store,resolveScope:async()=>scope,sourceFor:()=>({kind:'user-event',reference:'reader'})});const triggers=new EventTriggers({authorizeEvent:actor=>events.authorize(actor),readEvent:(actor,key)=>events.read(actor,{key})});
 const deferredStore=new DeferredTaskStore({pool});await deferredStore.initialize();let starts=0;const deferred=new DeferredTasks({store:deferredStore,resolveScope:async()=>scope,restoreActor:async()=>({id:'reader'}),validateInput:async()=>{},findTask:async()=>null,startTask:async()=>{starts++;return {id:randomUUID()};},triggers:triggerRouter({event:triggers})});
 const intent=await triggers.followUp(deferred,{}, {requestKey:'follow',trigger:{kind:'event',key:'input-ready'},input:{goal:'Continue with the event data'}});assert.equal((await deferred.tick()).state,'queued');assert.equal(starts,0);
 const event=await events.publish({}, {key:'input-ready',data:{codename:'Cobalt'}});assert.equal((await events.publish({}, {key:'input-ready',data:{codename:'Cobalt'}})).id,event.id);await pool.query('UPDATE iaic_deferred_tasks SET next_attempt_at=now() WHERE id=$1',[intent.id]);const dispatched=await deferred.tick();assert.equal(dispatched.state,'dispatched');assert.equal(dispatched.triggerReceipt.eventId,event.id);assert.equal(starts,1);
 assert.equal((await new EventStore({pool}).read(scope,{key:'input-ready'})).digest,event.digest);console.log(JSON.stringify({scopedImmutableEvent:true,waitsWithoutInference:true,durableReceipt:true,existingDispatcher:true,erpUsed:false}));
}finally{await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}
