import {AgentRuntime,TaskStore,CapabilityDispatcher,defineCapability,ContextAssembler,DeferredTaskStore,RecurringTaskStore,createAgentTaskSchedules,PostgresObservationStore,PostgresReleaseStore,ReleaseManager,ReleaseObservation,ReleaseMonitor,createReleaseMonitorCapability} from '@immedi/iaic-core';
export const actor={scopeId:'monitor-example',subjectId:'platform'},scope={applicationId:'monitor-example',assistantId:'operator',subjectId:'platform'};
export const digest='a'.repeat(64);
export async function openHost(pool,{loseAdmissionResponse=false,allowed=()=>true}={}){
 const tasks=new TaskStore({pool}),deferredStore=new DeferredTaskStore({pool,retryMs:0}),recurringStore=new RecurringTaskStore({pool,retryMs:0}),observations=new PostgresObservationStore({pool,namespace:'monitor-example'}),releaseStore=new PostgresReleaseStore({pool,namespace:'monitor-example'});
 await deferredStore.initialize();await recurringStore.initialize();await observations.initialize();await releaseStore.initialize();
 const evalPolicy={datasetDigest:'fixture',graderRevision:'fixture',environmentRevision:'fixture',repeats:1};
 const authorize=a=>a?.subjectId===actor.subjectId&&a.scopeId===actor.scopeId&&allowed();
 const releases=new ReleaseManager({store:releaseStore,evaluations:{get:async()=>null},policies:{capability:evalPolicy,regression:evalPolicy},authorize,resolveCohort:a=>a.subjectId});
 const observation=new ReleaseObservation({store:observations,releases,sourceScope:'fixture',authorize,policies:{production:{revision:'fixture-policy',fallbackId:'stable',minSamples:1,maxErrorRate:0,maxMeanLatencyMs:1000,windowMs:60000,maxAssessmentAgeMs:60000}},discoverSources:async()=>({sourceIds:['confirmed-run'],complete:true}),resolveSource:async sourceId=>({sourceId,sourceScope:'fixture',confirmed:true,record:{releaseId:'candidate',manifestDigest:digest,observedAt:(await releaseStore.get('candidate')).record.fixtureObservedAt,success:false,durationMs:10,toolErrors:1,providerTokens:'0',platformUnits:'0'}})});
 const monitor=new ReleaseMonitor({observation,authorize,autoProtect:true,resolveTarget:async(a,{channel})=>{const current=await releases.channel(a,channel),selected=await releases.resolve(a,channel);return {...selected,expectedRevision:current.revision};}});
 const monitorCapability=createReleaseMonitorCapability({monitor});
 const agent=defineCapability({name:'platform.observe',description:'Periodically inspect the host-approved production release',input:{type:'object',properties:{channel:{type:'string',const:'production'}},required:['channel'],additionalProperties:false},output:{type:'object',properties:{checked:{const:true}},required:['checked'],additionalProperties:false},effect:'write',retry:'idempotent',authorize,implementation:{kind:'agent',instructions:'Call observation.monitor for the supplied channel and finish only after the operation succeeds.',tools:[monitorCapability.name],allowCall:(input,action)=>action.input.channel===input.channel,verify:async(_input,_result,{history})=>history.calls.some(c=>c.capability===monitorCapability.name&&c.status==='succeeded'&&c.result.collectionComplete&&c.result.assessment.shouldStop&&c.result.protection.stableId==='stable')&&(await releaseStore.get('candidate')).disabled}});
 const dispatcher=new CapabilityDispatcher({capabilities:[monitorCapability,agent]});
 const model={name:'deterministic-monitor',next:async({billingContext})=>billingContext.turn===1?{type:'call',name:monitorCapability.name,input:{channel:'production'}}:{type:'finish',result:{checked:true}}};
 const runtime=new AgentRuntime({store:tasks,dispatcher,model,context:new ContextAssembler({}),version:'monitor-example-v1',maxTurns:3,maxCalls:1});dispatcher.tasks=runtime;await runtime.initialize();
 let lost=false;
 const scheduledDispatcher=Object.create(dispatcher);scheduledDispatcher.invoke=async(...args)=>{const result=await dispatcher.invoke(...args);if(loseAdmissionResponse&&!lost){lost=true;throw new Error('Fixture lost Task admission response');}return result;};
 const schedules=createAgentTaskSchedules({deferredStore,recurringStore,dispatcher:scheduledDispatcher,tasks,resolveScope:async a=>{if(!authorize(a))throw Object.assign(new Error('Scope denied'),{statusCode:403});return scope;},restoreActor:async saved=>{if(JSON.stringify(saved)!==JSON.stringify(scope))throw new Error('Scope binding mismatch');return actor;},authorize});
 return {runtime,tasks,releaseStore,...schedules};
}
