import {randomUUID} from 'node:crypto';import {Pool} from 'pg';
import {CrossPrincipalDelegations,PostgresWorkspaceStore,AssistantWorkspace,DelegationArtifacts,DelegationParents,TaskStore,AgentRuntime,ContextAssembler,CapabilityDispatcher,defineCapability,TokenLedger,AllowanceBudgets,PostgresDelegationStore,DelegatedCapabilities,DelegatedTasks,delegationExecutorKey} from '@immedi/iaic-core';
export async function fixture(fn,{reuseSchema=null}={}){
 const connectionString=process.env.SUBMISSION_TEST_DATABASE_URL;if(!connectionString)throw new Error('Isolated PostgreSQL required');const schema=reuseSchema||'delegated_task_'+randomUUID().replaceAll('-',''),admin=new Pool({connectionString});if(!reuseSchema)await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({connectionString,options:`-c search_path=${schema}`});let runtime,handoffs=null;
 try{
  if(!reuseSchema)await pool.query('CREATE TABLE effects(id text PRIMARY KEY,owner text)');
  const workspaceStore=new PostgresWorkspaceStore({pool});await workspaceStore.initialize();
  const workspace=new AssistantWorkspace({store:workspaceStore,resolveScope:a=>({applicationId:a.scopeId,subjectId:a.subjectId,assistantId:'fixture-job'}),sourceFor:()=>({kind:'fixture-task'})});let outputArtifact=null;
  const issuer={scopeId:'app',subjectId:'issuer'},delegate={scopeId:'app',subjectId:'delegate'},principal=a=>({applicationId:a.scopeId,subjectId:a.subjectId}),permitted=new Set(['issuer','delegate']);
  const ledger=new TokenLedger({pool});await ledger.initialize();const budgets=new AllowanceBudgets({ledger});ledger.budgets=budgets;await budgets.initialize();if(!reuseSchema)await ledger.grant(principal(issuer),{reference:'initial',amount:100,evidence:{fixture:true}});
  if(!reuseSchema)await budgets.create(principal(issuer),{id:'work',maximum:'10',executors:[delegationExecutorKey(principal(delegate))],deadlineAt:new Date(Date.now()+60000).toISOString(),overflow:'platform_absorbs'});
  const object={type:'object'},cap=defineCapability({name:'records.write',description:'Fixture effect',input:object,output:object,effect:'write',retry:'never-replay',authorize:a=>permitted.has(a.subjectId),revalidate:async(_i,r)=>r,implementation:{kind:'function',execute:async(i,c)=>{await pool.query('INSERT INTO effects VALUES($1,$2)',[c.callId,c.actor.subjectId]);outputArtifact=await workspace.write(c.actor,{path:'output.md',content:'Verified delegated output',mediaType:'text/markdown'});return {done:true};}}});
  const agent=defineCapability({name:'worker.run',description:'Fixture worker',input:object,output:object,effect:'write',retry:'never-replay',authorize:a=>permitted.has(a.subjectId),implementation:{kind:'agent',instructions:'Write once then finish',tools:['records.write'],verify:async()=>Number((await pool.query('SELECT count(*) FROM effects')).rows[0].count)===1}});
  const dispatcher=new CapabilityDispatcher({capabilities:[cap,agent]}),grantStore=new PostgresDelegationStore({pool,namespace:'fixture'});await grantStore.initialize();
  const grants=new DelegatedCapabilities({store:grantStore,dispatcher,resolvePrincipal:principal,restoreActor:r=>({scopeId:r.applicationId,subjectId:r.subjectId}),authorizeGrant:()=>true,allowInput:()=>true});
  const authority=new DelegatedTasks({grants,ledger,modelPolicy:()=>({mode:'SYSTEM_MANAGED',policy:{maximum:'5',price:{revision:'fixture',input:'1',cachedInput:'1',output:'1'}}})});
  const input={goal:'Write the fixture record and verify it',allowedTools:['records.write']};
  if(!reuseSchema)await grants.issue(issuer,{id:'task-grant',delegate:principal(delegate),payer:principal(issuer),tools:['records.write'],constraints:{},deadlineAt:new Date(Date.now()+60000).toISOString(),maxCalls:1,task:{capability:agent.name,input,budgetId:'work'}});
  let modelCalls=0;const model={name:'fixture-model',next:async r=>{modelCalls++;if(r.billingContext.capability==='parent.run')return {type:'wait',question:'Delegate the scoped work',usage:{inputTokens:1,outputTokens:1}};return {...(!outputArtifact?{type:'call',name:'records.write',input:{}}:{type:'finish',result:{done:true,summary:'Produced an artifact',artifacts:outputArtifact?[outputArtifact.reference]:[]}}),usage:{inputTokens:1,outputTokens:1}};}};
  const build=async(enabled=true)=>{if(runtime)await runtime.stop();runtime=new AgentRuntime({store:new TaskStore({pool}),dispatcher,model,handoffs,authority:enabled?authority:null,context:new ContextAssembler({skillRoot:'/tmp',handoffProvider:({actor,task})=>handoffs?.context(actor,task.id)}),version:'fixture-v1'});dispatcher.tasks=runtime;await runtime.initialize();return runtime;};
  await build();await fn({schema,issuer,delegate,authority,grants,grantStore,dispatcher,workspace,ledger,budgets,principal,pool,build,permitted,model,setHandoffs:value=>{handoffs=value;},modelCalls:()=>modelCalls,getRuntime:()=>runtime});
 }finally{if(runtime)await runtime.stop();await pool.end();if(!reuseSchema)await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}
}
