import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {Pool} from 'pg';
import {TaskStore} from '@immedi/iaic-core/tasks/store.js';import {AgentRuntime} from '@immedi/iaic-core/agent/runtime.js';import {ContextAssembler} from '@immedi/iaic-core/context/index.js';import {defineCapability,CapabilityDispatcher} from '@immedi/iaic-core/capabilities/index.js';
const admin=new Pool({connectionString:process.env.DATABASE_URL}),schema='handoff_example_'+randomUUID().replaceAll('-','');await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({connectionString:process.env.DATABASE_URL,options:`-c search_path=${schema}`});const hosts=[];let unblock,entered;const paused=new Promise(r=>entered=r),release=new Promise(r=>unblock=r);
try{
 const actor={scopeId:'app',subjectId:'user'},cap=defineCapability({name:'agent.work',description:'Fixture',input:{type:'object'},output:{type:'object'},effect:'read',authorize:()=>true,implementation:{kind:'agent',instructions:'Fixture',tools:[],verify:()=>true}});
 const open=async handoff=>{const store=new TaskStore({pool}),dispatcher=new CapabilityDispatcher({capabilities:[cap]}),runtime=new AgentRuntime({store,dispatcher,version:'v1',context:new ContextAssembler({skillRoot:'/tmp'}),model:{name:'fixture',next:async()=>{if(!handoff){entered();await release;}return {type:'finish',result:{done:true}};}}});dispatcher.tasks=runtime;hosts.push(runtime);await runtime.initialize({requestHandoff:handoff});return runtime;};
 const old=await open(false);const task=await old.dispatcher.invoke('agent.work',{}, {actor,callId:'original'});const inflight=old.tick();await paused;
 const next=await open(true);assert.equal(next.ready,false);assert.equal((await next.deploymentState()).ownership.state,'draining');
 const queued=await next.dispatcher.invoke('agent.work',{}, {actor,callId:'successor'});assert.equal(await next.tick(),null);assert.equal((await next.store.get(actor,task.id)).status,'running');
 unblock();await inflight;assert.equal(await old.tick(),null);assert.equal((await next.tick()).id,queued.id);assert.equal((await next.deploymentState()).generation,'2');assert.equal((await next.store.history(actor,task.id)).events.some(e=>e.kind==='interrupted'),false);
 assert.deepEqual(await next.drain({timeoutMs:100}),{drained:true,requiresTermination:false});console.log(JSON.stringify({executorHandoff:true,oldRetired:true,inflightCompleted:true,queuedTaskTransferred:true,prematureRecovery:false,modelMode:'deterministic',liveDeployment:false}));
}finally{unblock();for(const host of hosts)await host.stop();await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}
