import {assessmentTool} from './assessment.js';
import {memoryImportSchema} from './import-format.js';
// Protocol descriptors live with the feature, not in the platform singleton.
export function memoryTools(memory,actor){
 const projectedFields={
  my_remember_assistant_memory:['key','kind','expectedRevision','expiresAt'],
  my_relearn_assistant_memory:['key','kind','expectedRevision','expiresAt'],
  my_resolve_assistant_memory_dispute:['key','kind','expectedRevision','expiresAt'],
  my_dispute_assistant_memory:['key','expectedRevision'],
  my_import_assistant_memories:['requestKey'],
  my_list_assistant_memories:['status','limit','kind']
 };
 const tool=(name,description,inputSchema,handler)=>({name,description,inputSchema,handler,
  ...(projectedFields[name]?{projectHistoryInput:input=>Object.fromEntries(projectedFields[name].filter(key=>input&&typeof input==='object'&&Object.hasOwn(input,key)).map(key=>[key,input[key]]))}:{})});
 return [
   ...(memory?.assessmentEnabled?[assessmentTool(memory,actor)]:[]),
   tool('my_dispute_assistant_memory','Mark an active memory as disputed using its current revision and a user-supplied reason. It leaves automatic memory retrieval/export until explicit correction; no truth is inferred.',{type:'object',properties:{key:{type:'string',minLength:1,maxLength:200},reason:{type:'string',minLength:1,maxLength:2000},expectedRevision:{type:'integer',minimum:1}},required:['key','reason','expectedRevision'],additionalProperties:false},value=>memory.dispute(actor,value)),
   tool('my_resolve_assistant_memory_dispute','Explicitly replace a disputed memory with newly supplied user content at its current revision. The new statement is not a verified business fact. Ordinary remember cannot silently resolve disputes.',{type:'object',properties:{key:{type:'string',minLength:1,maxLength:200},kind:{enum:['fact','preference','note']},content:{type:'string',minLength:1,maxLength:8000},expectedRevision:{type:'integer',minimum:1},expiresAt:{type:['string','null']}},required:['key','kind','content','expectedRevision'],additionalProperties:false},value=>memory.resolveDispute(actor,value)),
   tool('my_read_assistant_memory','Read one exact memory key and its current revision/status. Disputed or contradicted content is shown only as a contested statement with its reason, not an accepted fact. Forgotten or expired memory returns metadata with null content/source; absence returns not found. This does not restore old content.',{type:'object',properties:{key:{type:'string',minLength:1,maxLength:200}},required:['key'],additionalProperties:false},value=>memory.read(actor,value)),
   tool('my_relearn_assistant_memory','Record new content explicitly supplied by the user for a forgotten memory key. Requires its current forgotten revision and new kind/content. Old content is not recoverable. Ordinary writes and import replay cannot perform this transition.',{type:'object',properties:{key:{type:'string',minLength:1,maxLength:200},kind:{enum:['fact','preference','note']},content:{type:'string',minLength:1,maxLength:8000},expectedRevision:{type:'integer',minimum:1},expiresAt:{type:['string','null']}},required:['key','kind','content','expectedRevision'],additionalProperties:false},value=>memory.relearn(actor,value)),
   tool('my_import_assistant_memories','Import a v1 memory export explicitly requested by the user. Creates new keys atomically, never overwrites existing or forgotten keys. Expired rows are skipped. Imported source claims do not become authoritative facts. Same requestKey and snapshot replay returns the original receipt without restoring later-forgotten content.',memoryImportSchema,value=>memory.import(actor,value)),
   tool('my_export_assistant_memories','Export this user active Assistant memories with source and revision metadata.',{type:'object',properties:{},additionalProperties:false},()=>memory.export(actor)),
   tool('my_list_assistant_memories','Read this user assistant memories. Default status is active; explicitly select disputed or contradicted to review unresolved claims, never treat those as settled facts. Omit query to list recent memories; query is a literal content substring, not semantic search. User statements are not authoritative business facts.',{type:'object',properties:{status:{type:'string',enum:['active','disputed','contradicted']},query:{type:'string',maxLength:500,description:'Literal substring in memory content. Omit to inspect recent memories; an empty result does not prove no relevant memory exists.'},limit:{type:'integer',minimum:1,maximum:50}},additionalProperties:false},value=>memory.list(actor,value)),
   tool('my_remember_assistant_memory','Save a memory explicitly requested by this user. Do not convert inferred preferences into authorization.',{type:'object',properties:{key:{type:'string',minLength:1,maxLength:200},kind:{type:'string',enum:['fact','preference','note']},content:{type:'string',minLength:1,maxLength:8000},expectedRevision:{type:'integer',minimum:0},expiresAt:{type:['string','null']}},required:['key','kind','content'],additionalProperties:false},value=>memory.remember(actor,value)),
   tool('my_forget_assistant_memory','Forget this user memory using its current revision.',{type:'object',properties:{key:{type:'string',minLength:1,maxLength:200},expectedRevision:{type:'integer',minimum:1}},required:['key','expectedRevision'],additionalProperties:false},value=>memory.forget(actor,value))
 ];
}
