import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {Pool} from 'pg';
import {DeferredTaskStore,DeferredTasks,TaskStore,createDeferredScheduleCapability,createDeferredControlCapabilities} from '@immedi/iaic-core';
const connectionString=process.env.DATABASE_URL||process.env.SUBMISSION_TEST_DATABASE_URL;if(!connectionString)throw new Error('Isolated PostgreSQL URL required');
const admin=new Pool({connectionString}),schema='deferred_example_'+randomUUID().replaceAll('-','');await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({connectionString,options:`-c search_path=${schema}`});
try{
 const scope={applicationId:'draft-demo',assistantId:'helper',subjectId:'reader'},actor={scopeId:'draft-demo',subjectId:'reader'},store=new DeferredTaskStore({pool}),tasks=new TaskStore({pool});await store.initialize();await tasks.initialize();
 const ports={store,resolveScope:async()=>scope,restoreActor:async()=>actor,validateInput:async()=>{},findTask:(actor,key)=>tasks.findRequest(actor,'draft',key),startTask:(actor,input,key)=>tasks.create({actor,capability:'draft',input,idempotencyKey:key,version:'example-v1',model:'fixture'})};
 const first=new DeferredTasks({...ports,reservedPrefixes:['agent-call:']}),capability=createDeferredScheduleCapability({deferred:first,authorize:async()=>true,taskSchema:{type:'object',properties:{goal:{type:'string'}},required:['goal'],additionalProperties:false}}),request={dueAt:'2020-01-01T00:00:00Z',task:{goal:'Draft a note'}},context={actor,callId:'example-call'},row=await capability.implementation.execute(request,context);assert.equal((await capability.reconcile(request,context)).result.id,row.id);assert.equal((await tasks.list(actor)).length,0);
 const restored=new DeferredTasks(ports),receipt=await restored.tick();assert.equal(receipt.id,row.id);assert.equal(receipt.state,'dispatched');assert.equal((await tasks.get(actor,receipt.taskId)).status,'queued');assert.equal(await restored.tick(),null);assert.equal((await tasks.list(actor)).length,1);
 const controls=createDeferredControlCapabilities({deferred:restored,authorize:async()=>true});const view=await controls.find(c=>c.name==='my_get_scheduled_assistant_task').implementation.execute({id:row.id},{actor});assert.equal(view.taskId,receipt.taskId);const pending=await restored.schedule(actor,{requestKey:'cancel-example',dueAt:'2099-01-01T00:00:00Z',input:{goal:'Cancel this intent'}});const cancelled=await controls.find(c=>c.name==='my_cancel_scheduled_assistant_task').implementation.execute({id:pending.id},{actor});assert.equal(cancelled.state,'cancelled');
 console.log(JSON.stringify({application:'core-deferred',scheduleControls:true,scheduleCapability:true,durableIntent:true,existingTaskStore:true,singleTask:true,erpUsed:false,modelInvoked:false}));
}finally{await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}
