import {eventKeySchema} from '../events/tools.js';
const fail=(message,statusCode=400)=>Object.assign(new Error(message),{statusCode});
export class EventTriggers {
 constructor({readEvent,authorizeEvent}){Object.assign(this,{readEvent,authorizeEvent});}
 async normalize(actor,trigger){if(!trigger||trigger.kind!=='event'||typeof trigger.key!=='string'||!trigger.key.trim()||trigger.key.length>200||Object.keys(trigger).some(k=>!['kind','key'].includes(k)))throw fail('Explicit event key required');if(await this.authorizeEvent(actor,trigger.key)!==true)throw fail('Event access denied',403);return {kind:'event',key:trigger.key};}
 async check(actor,trigger){const value=await this.normalize(actor,trigger);let event;try{event=await this.readEvent(actor,value.key);}catch(e){if(e.statusCode===404)return null;throw e;}
  if(event.key!==value.key||typeof event.id!=='string'||!/^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/i.test(event.id)||!/^([0-9a-f]{64})$/.test(event.digest)||!Number.isFinite(Date.parse(event.publishedAt)))throw fail('Invalid event receipt',409);
  return {kind:'event',key:value.key,eventId:event.id,digest:event.digest,publishedAt:new Date(event.publishedAt).toISOString()};
 }
 async followUp(deferred,actor,{requestKey,trigger,input}){const value=await this.normalize(actor,trigger);if(!input||typeof input!=='object'||Array.isArray(input))throw fail('Task input required');if(input.sourceEventKey!==undefined&&input.sourceEventKey!==value.key)throw fail('Goal event differs from trigger',409);return deferred.schedule(actor,{requestKey,dueAt:'1970-01-01T00:00:00.000Z',trigger:value,input:{...input,sourceEventKey:value.key}});}
}
export function triggerRouter(handlers){const resolve=trigger=>{const handler=Object.hasOwn(handlers,trigger?.kind)?handlers[trigger.kind]:null;if(!handler)throw fail('Unsupported trigger kind');return handler;};return {normalize:(actor,trigger)=>resolve(trigger).normalize(actor,trigger),check:(actor,trigger)=>resolve(trigger).check(actor,trigger)};}
export function eventFollowupTool(triggers,deferred,actor,taskSchema){return {name:'my_follow_up_assistant_event',description:'Save a one-time goal to run when a scoped event key exists. May be registered before publication; an already-published event also matches. sourceEventKey is pinned. Uses existing scheduled-task query/cancel/retry; event receipt proves publication, not business truth.',inputSchema:{type:'object',properties:{requestKey:{type:'string',minLength:1,maxLength:200},trigger:{type:'object',properties:{kind:{const:'event'},key:eventKeySchema},required:['kind','key'],additionalProperties:false},input:{...taskSchema,required:[...new Set([...taskSchema.required,'allowedTools'])]}},required:['requestKey','trigger','input'],additionalProperties:false},handler:input=>triggers.followUp(deferred,actor,input)};}
