import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {Pool} from 'pg';
import {HandoffStore,TaskHandoffs,TaskStore,AgentRuntime,ContextAssembler,CapabilityDispatcher,defineCapability} from '@immedi/iaic-core';
const admin=new Pool({connectionString:process.env.DATABASE_URL}),schema='handoff_example_'+randomUUID().replaceAll('-','');await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({connectionString:process.env.DATABASE_URL,options:`-c search_path=${schema}`});let runtime;
try{
 const actor={scopeId:'neutral',subjectId:'owner'},tasks=new TaskStore({pool}),store=new HandoffStore({pool});await store.initialize();
 const read=defineCapability({name:'note.read',description:'Read source note',input:{type:'object'},output:{type:'object'},effect:'read',authorize:async a=>a.subjectId==='owner',revalidate:async()=>({text:'Prepare agenda'}),implementation:{kind:'function',execute:async()=>({text:'Prepare agenda'})}});
 const agent=name=>defineCapability({name,description:name,input:{type:'object'},output:{type:'object'},effect:'write',retry:'never-replay',authorize:async a=>a.subjectId==='owner',implementation:{kind:'agent',tools:['note.read'],instructions:'Use the note as evidence',verify:async(_i,_r,{history})=>name==='coordinator'||history.calls.some(c=>c.capability==='note.read'&&c.status==='succeeded')}});
 const dispatcher=new CapabilityDispatcher({capabilities:[read,agent('coordinator'),agent('specialist')]});let steps=0;
 const ports={store,resolveScope:async a=>({applicationId:a.scopeId,subjectId:a.subjectId}),restoreActor:async s=>({scopeId:s.applicationId,subjectId:s.subjectId}),authorize:async a=>a.subjectId==='owner',attenuateInput:async({input})=>input,readTask:(a,id)=>runtime.get(a,id,{history:true}),readTaskState:(a,id)=>runtime.state(a,id),admitTask:(a,name,input,key)=>dispatcher.invoke(name,input,{actor:a,callId:key}),findTask:(a,name,key)=>tasks.findRequest(a,name,key),cancelTask:(a,id)=>runtime.transition(a,id,{action:'cancel'}),capabilityFor:name=>dispatcher.capabilities.get(name),readArtifact:async()=>{throw new Error('This minimal host has no artifact store');}};
 const handoffs=new TaskHandoffs(ports);
 const model={name:'deterministic-handoff',next:async request=>{steps++;if(steps===5){assert.ok(request.delegationSchema);return {type:'delegate',input:{goal:'Read the source note',successCriteria:'Summarize the note after reading it',tools:['note.read']}};}if(steps===1)return {type:'wait',question:'Coordinator private context'};if(steps===4||steps===8){const data=JSON.parse(request.messages[1].content);assert.equal(data.handoffs.items[0].result.summary,'Read the agenda preparation note');return {type:'finish',result:{summary:'Continued from child evidence',artifacts:[]}};}assert.doesNotMatch(JSON.stringify(request.messages),/Coordinator private context/);assert.deepEqual(request.tools.map(t=>t.name),['note.read']);return [2,6].includes(steps)?{type:'call',name:'note.read',input:{}}:{type:'finish',result:{summary:'Read the agenda preparation note',artifacts:[]}};}};
 runtime=new AgentRuntime({store:tasks,dispatcher,model,context:new ContextAssembler({skillRoot:process.cwd(),handoffProvider:({actor,task})=>task.handoff?null:handoffs.context(actor,task.id)}),version:'handoff-example-v1',handoffs});dispatcher.tasks=runtime;await runtime.initialize();
 const parent=await dispatcher.invoke('coordinator',{goal:'Coordinator private context',allowedTools:['note.read']},{actor,callId:'parent'});assert.equal((await runtime.tick()).status,'waiting');
 const input={requestKey:'child',parentTaskId:parent.id,capability:'specialist',goal:'Read the source note',successCriteria:'Summarize the note after reading it',tools:['note.read'],maxModelCalls:2,deadlineAt:'2099-01-01T00:00:00Z'};
 const receipt=await handoffs.create(actor,input);assert.equal((await handoffs.create(actor,input)).childTaskId,receipt.childTaskId);assert.equal((await runtime.tick()).status,'succeeded');
 const rebuilt=new TaskHandoffs({...ports,store:new HandoffStore({pool})}),result=await rebuilt.read(actor,receipt.id);assert.equal(result.childStatus,'succeeded');assert.equal(result.modelAdmissionsUsed,2);assert.equal((await tasks.list(actor)).length,2);assert.equal(steps,3);
 await runtime.transition(actor,parent.id,{action:'provide_input',input:'Continue the original goal.'});assert.equal((await runtime.tick()).status,'succeeded');assert.equal(steps,4);
 const automatic=await dispatcher.invoke('coordinator',{goal:'Delegate one note read',allowedTools:['note.read'],delegation:{capability:'specialist',maxModelCalls:2,timeoutMs:120000}},{actor,callId:'automatic'});assert.equal((await runtime.tick()).waiting_reason,'external_result');assert.equal((await runtime.tick()).status,'succeeded');assert.equal((await runtime.tick()).id,automatic.id);const completed=await runtime.get(actor,automatic.id,{history:true});assert.equal(completed.status,'succeeded');assert.equal(completed.events.filter(e=>e.kind==='input').length,0);assert.equal(steps,8);
 console.log(JSON.stringify({modelInitiatedDelegation:true,noOwnerResume:true,parentReceivesCurrentChildEvidence:true,persistentHandoff:true,sameRuntime:true,independentChildContext:true,stableReceipt:true,boundedModelAdmissions:2,erpUsed:false,modelMode:'deterministic'}));
}finally{await runtime?.stop();await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}
