import {defineCapability} from '../capabilities/index.js';
const ref={type:'object',properties:{sha256:{type:'string',pattern:'^[a-f0-9]{64}$'},byteLength:{type:'integer',minimum:0}},required:['sha256','byteLength'],additionalProperties:false};
export function createObjectCapabilities({storage,prefix='objects',maxTransferBytes=1048576}){
 if(!Number.isSafeInteger(maxTransferBytes)||maxTransferBytes<1)throw new Error('Positive object transfer limit required');
 const read=async(input,{actor})=>{if(input.byteLength>maxTransferBytes)throw Object.assign(new Error('Object exceeds capability transfer limit'),{statusCode:413});const bytes=await storage.get(actor,input);return {reference:input,base64:Buffer.from(bytes).toString('base64')};};
 return [defineCapability({name:prefix+'.put',description:'Store scoped binary content as base64 and return its exact content reference. Not a logical Workspace path or a permission grant.',input:{type:'object',properties:{base64:{type:'string',maxLength:4*Math.ceil(maxTransferBytes/3)}},required:['base64'],additionalProperties:false},output:ref,effect:'write',retry:'idempotent',authorize:async()=>true,implementation:{kind:'function',execute:async(input,{actor})=>{const bytes=Buffer.from(input.base64,'base64');if(bytes.toString('base64')!==input.base64||bytes.length>maxTransferBytes)throw Object.assign(new Error('Canonical base64 within transfer limit required'),{statusCode:400});return storage.put(actor,bytes);}}}),
 defineCapability({name:prefix+'.get',description:'Read and verify scoped object bytes by exact digest and size. Base64 is transport encoding, not interpreted content.',input:ref,output:{type:'object',properties:{reference:ref,base64:{type:'string'}},required:['reference','base64'],additionalProperties:false},effect:'read',authorize:async()=>true,revalidate:(input,_old,context)=>read(input,context),implementation:{kind:'function',execute:read}}),
 defineCapability({name:prefix+'.remove',description:'Remove a scoped object. Existing references stop resolving until explicit re-upload; downloaded copies are not erased.',input:ref,output:{type:'object',properties:{removed:{type:'boolean'}},required:['removed'],additionalProperties:false},effect:'write',retry:'never-replay',authorize:async()=>true,implementation:{kind:'function',execute:(input,{actor})=>storage.remove(actor,input)}})];
}
