import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';import {createServer} from 'node:http';import {randomUUID,randomBytes} from 'node:crypto';import {Pool} from 'pg';
import {AgentRuntime,TaskStore,ContextAssembler,CapabilityDispatcher,defineCapability,createTaskControlCapabilities,TaskListing,createTaskListCapability,createCapabilityHttpHandler} from '@immedi/iaic-core';
import {CapabilityHttpClient} from '@immedi/iaic-core/http/client.js';
const {IAIC_BROWSER_HOST_PACKAGE:hostPackage,IAIC_BROWSER_EXECUTABLE:executablePath,IAIC_BROWSER_EVIDENCE:directory,SUBMISSION_TEST_DATABASE_URL:connectionString}=process.env;
if(!hostPackage||!path.isAbsolute(hostPackage)||!executablePath||!directory||!connectionString||!['localhost','127.0.0.1','[::1]'].includes(new URL(connectionString).hostname))throw Error('Explicit browser host package, executable, fresh evidence directory and local isolated PostgreSQL required');
const puppeteer=createRequire(hostPackage)('puppeteer-core');await fs.mkdir(directory,{recursive:true,mode:0o700});
const schema='ui_bindings_'+randomUUID().replaceAll('-',''),admin=new Pool({connectionString});await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({connectionString,options:`-c search_path=${schema}`});let runtime,browser,server;
try{
 await pool.query('CREATE TABLE fixture_records(id uuid PRIMARY KEY,owner text NOT NULL,request_key text NOT NULL,value integer NOT NULL,UNIQUE(owner,request_key))');
 const actor={scopeId:'ui-fixture',subjectId:'fixture-user'},cursorKey=randomBytes(32);let allowed=true,modelCalls=0;
 const authorize=a=>allowed&&a.scopeId===actor.scopeId&&a.subjectId===actor.subjectId,store=new TaskStore({pool});
 const save=defineCapability({name:'record.save',description:'Create one fixture record',input:{type:'object',properties:{value:{type:'integer'}},required:['value'],additionalProperties:false},output:{type:'object'},effect:'write',retry:'idempotent',authorize,revalidate:async(_i,r)=>r,implementation:{kind:'function',execute:async(input,{actor,callId})=>{
  await pool.query('INSERT INTO fixture_records(id,owner,request_key,value) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[randomUUID(),actor.subjectId,callId,input.value]);const row=(await pool.query('SELECT id,value FROM fixture_records WHERE owner=$1 AND request_key=$2',[actor.subjectId,callId])).rows[0];if(row.value!==input.value)throw Object.assign(new Error('Request conflict'),{statusCode:409});return row;
 }}});
 const agent=defineCapability({name:'work.run',description:'Create the user-confirmed fixture record',input:{type:'object',properties:{goal:{type:'string',minLength:1}},required:['goal'],additionalProperties:false},output:{type:'object'},effect:'write',retry:'never-replay',authorize,implementation:{kind:'agent',instructions:'Ask the user for confirmation before writing the fixture record.',tools:[save.name],verify:async(_i,r)=>r.value===42&&Boolean((await pool.query('SELECT id FROM fixture_records WHERE id=$1 AND owner=$2 AND value=42',[r.id,actor.subjectId])).rowCount)}});
 const controls=createTaskControlCapabilities({runtime:{get:(...args)=>runtime.get(...args),state:(...args)=>runtime.state(...args),transition:(...args)=>runtime.transition(...args),transitionReceipt:(...args)=>runtime.transitionReceipt(...args)},authorize,receipts:true});
 const listing=new TaskListing({store,readTask:(actor,id)=>runtime.state(actor,id),resolveOwner:a=>JSON.stringify([a.scopeId,a.subjectId]),cursorKey}),list=createTaskListCapability({listing,authorize});
 const dispatcher=new CapabilityDispatcher({capabilities:[agent,save,...controls,list]});
 const model={name:'ui-fixture',next:async({messages})=>{modelCalls++;const context=JSON.parse(messages.find(m=>m.role==='user').content);if(!context.events.some(e=>e.kind==='input'))return {type:'wait',question:'Please confirm that the record should contain value 42.'};if(!context.calls.length)return {type:'call',name:save.name,input:{value:42}};return {type:'finish',result:context.calls[0].result};}};
 const rebuild=async()=>{await runtime?.stop();runtime=new AgentRuntime({store:new TaskStore({pool}),dispatcher,model,context:new ContextAssembler({skillRoot:directory}),version:'ui-v1'});dispatcher.tasks=runtime;await runtime.initialize();};await rebuild();
 const publicNames=[agent.name,list.name,...controls.map(c=>c.name)],handler=createCapabilityHttpHandler({dispatcher,resolveAccess:req=>req.headers.get('authorization')==='Bearer fixture-ui'?{actor,capabilities:publicNames}:null});
 const html=await fs.readFile(new URL('./index.html',import.meta.url)),clientSource=await fs.readFile(new URL(import.meta.resolve('@immedi/iaic-core/http/client.js')));
 server=createServer(async(req,res)=>{try{if(req.method==='GET'&&['/','/client.js'].includes(req.url)){res.setHeader('content-type',req.url==='/'?'text/html; charset=utf-8':'text/javascript');res.end(req.url==='/'?html:clientSource);return;}const chunks=[];for await(const c of req)chunks.push(c);const response=await handler(new Request(origin+req.url,{method:req.method,headers:req.headers,...(chunks.length?{body:Buffer.concat(chunks)}:{})}));res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch{res.writeHead(500);res.end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;
 browser=await puppeteer.launch({executablePath,headless:true});
 const openPage=async()=>{const page=await browser.newPage();await page.setViewport({width:960,height:900});await page.setRequestInterception(true);page.on('request',req=>req.url().startsWith(origin+'/')?req.continue():req.abort());await page.goto(origin);await page.waitForFunction(()=>window.fixtureReady===true);return page;};
 let page=await openPage();const click=async(id)=>{await page.click('#'+id);await page.waitForFunction(()=>['ok','error'].includes(document.querySelector('#output').dataset.state));return page.$eval('#output',element=>JSON.parse(element.textContent));};
 const first=await click('submit');assert.equal(first.status,'queued');assert.equal((await click('submit')).id,first.id);await page.close();assert.equal((await runtime.tick()).status,'waiting');
 page=await openPage();await click('discover');const waiting=await click('read');assert.equal(waiting.id,first.id);assert.equal(waiting.inputRequest.question,'Please confirm that the record should contain value 42.');assert.equal(await page.$eval('#question',e=>e.textContent),waiting.inputRequest.question);await page.screenshot({path:path.join(directory,'waiting.png'),fullPage:true});
 await page.type('#clarification','Confirmed: use value 42.');const accepted=await click('answer');assert.equal(accepted.status,'queued');assert.ok(accepted.controlReceipt);await page.close();await rebuild();assert.equal((await runtime.tick()).status,'succeeded');
 page=await openPage();await click('discover');const completed=await click('read');assert.equal(completed.id,first.id);assert.equal(completed.status,'succeeded');assert.equal(completed.inputRequest,null);assert.equal(completed.result.value,42);
 const sdk=new CapabilityHttpClient({url:origin+'/capabilities',headers:()=>({authorization:'Bearer fixture-ui'})});assert.deepEqual((await sdk.invoke('tasks.get',{id:first.id})).result,completed);assert.equal(Number((await pool.query('SELECT count(*) FROM fixture_records')).rows[0].count),1);assert.equal((await store.history(actor,first.id)).events.filter(e=>e.kind==='input').length,1);await page.screenshot({path:path.join(directory,'completed.png'),fullPage:true});
 const pending=await click('submit');assert.notEqual(pending.id,first.id);assert.equal((await click('cancel')).status,'cancelled');assert.equal((await sdk.invoke('tasks.state',{id:pending.id})).result.status,'cancelled');
 allowed=false;assert.equal((await click('read')).statusCode,403);await assert.rejects(sdk.invoke('tasks.get',{id:first.id}),{statusCode:403});assert.equal(modelCalls,3);
 const result={example:'core-ui-bindings',status:'passed',browser:await browser.version(),realBrowser:true,uiSdkSameTask:true,taskContinuedWithPageClosed:true,pendingQuestionVisible:true,originalClarificationReceipt:true,verifiedSharedResult:true,cancellation:true,currentRevocation:true,domainEffects:1,modelCalls,actualModel:false,processKill:false,productionAccessed:false};await fs.writeFile(path.join(directory,'result.json'),JSON.stringify(result,null,2),{flag:'wx',mode:0o600});console.log(JSON.stringify(result));
}finally{await browser?.close();await runtime?.stop();if(server){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}
