import {createServer} from 'node:http';
import {Pool} from 'pg';
import {createApplicationHttpHandler} from './http.mjs';
import {openApplication} from './app.mjs';
import {optionsFromEnvironment} from './config.mjs';
if(!process.env.DATABASE_URL||!process.env.APP_TOKEN)throw new Error('Set DATABASE_URL and APP_TOKEN');
const pool=new Pool({connectionString:process.env.DATABASE_URL}),options=optionsFromEnvironment(),app=await openApplication({pool,...options});
const actor={subjectId:process.env.APP_SUBJECT,scopeId:process.env.APP_ORGANIZATION};
const handler=createApplicationHttpHandler({app,job:options.job,resolveActor:request=>request.headers.get('authorization')==='Bearer '+process.env.APP_TOKEN?actor:null});
const server=createServer(async(req,res)=>{try{let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>1048576){res.writeHead(413).end();return;}chunks.push(chunk);}const method=req.method||'GET';const response=await handler(new Request('http://localhost'+req.url,{method,headers:req.headers,signal:AbortSignal.timeout(30000),...(!['GET','HEAD'].includes(method)?{body:Buffer.concat(chunks)}:{})}));res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch{res.writeHead(500).end();}});
app.start();server.listen(Number(process.env.PORT||3000),'127.0.0.1',()=>console.log('Persistent Agent server listening locally'));
let closing=false;async function close(){if(closing)return;closing=true;await new Promise(resolve=>server.close(resolve));await app.close();await pool.end();}process.once('SIGINT',close);process.once('SIGTERM',close);
